# Generated by Django 5.2.6 on 2025-10-29 19:21

import base.utils.image_upload
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_form', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('user', 'User'), ('owner', 'Owner'), ('admin', 'Admin')], default='user', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=base.utils.image_upload.user_avatar_path, validators=[base.utils.image_upload.ImageValidator(max_size_mb=2)])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=base.utils.image_upload.school_logo_path, validators=[base.utils.image_upload.ImageValidator(max_size_mb=5)])),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('street', models.CharField(max_length=255)),
                ('build_no', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('full_address', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('important_info', models.TextField(blank=True, null=True)),
                ('rules', models.TextField(blank=True, null=True)),
                ('default_registration_info_link', models.TextField(blank=True, null=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school', to=settings.AUTH_USER_MODEL)),
                ('styles', models.ManyToManyField(blank=True, related_name='schools', to='base.style')),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_duration', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list', to='base.school')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('pseudonym', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=base.utils.image_upload.instructor_image_path, validators=[base.utils.image_upload.ImageValidator(max_size_mb=5)])),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='base.school')),
                ('styles', models.ManyToManyField(blank=True, related_name='instructors', to='base.style')),
            ],
        ),
        migrations.CreateModel(
            name='DanceFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='base.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=base.utils.image_upload.school_image_path, validators=[base.utils.image_upload.ImageValidator(max_size_mb=5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.school')),
            ],
        ),
        migrations.CreateModel(
            name='DanceClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(blank=True, choices=[('monday', 'Poniedziałek'), ('tuesday', 'Wtorek'), ('wednesday', 'Środa'), ('thursday', 'Czwartek'), ('friday', 'Piątek'), ('saturday', 'Sobota'), ('sunday', 'Niedziela')], max_length=20, null=True)),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('first_class_date', models.DateField(blank=True, null=True)),
                ('can_join', models.BooleanField(default=True)),
                ('periodic', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('registration_info_link', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.agegroup')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.dancefloor')),
                ('instructors', models.ManyToManyField(blank=True, related_name='classes', to='base.instructor')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.level')),
                ('participation_form', models.ForeignKey(blank=True, help_text='Opcjonalnie, np. zajęcia w parach, solo, formacja', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.participationform')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='base.school')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='base.style')),
            ],
        ),
        migrations.CreateModel(
            name='ClassCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Konkretna data, w której zajęcia się nie odbędą.')),
                ('reason', models.CharField(blank=True, help_text="Opcjonalny powód odwołania (np. 'Święto').", max_length=255, null=True)),
                ('cancelled', models.BooleanField(default=True, help_text='Zaznaczone oznacza, że zajęcia są odwołane. Odznacz, aby przywrócić zajęcia w tym terminie.')),
                ('dance_class', models.ForeignKey(help_text='Wybierz zajęcia, które chcesz odwołać.', on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='base.danceclass')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('dance_class', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='base.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('school', 'user')},
            },
        ),
    ]
