# Generated by Django 5.2.6 on 2026-01-11 20:14

import base.utils.image_upload
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('user', 'User'), ('owner', 'Owner'), ('admin', 'Admin')], default='user', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=base.utils.image_upload.school_logo_path, validators=[base.utils.image_upload.ImageValidator(max_size_mb=5)])),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('street', models.CharField(max_length=255)),
                ('build_no', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('full_address', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(help_text='Opisz klimat swojego studia, co Was wyróżnia oraz najważniejsze informacje. To tekst, który ma przekonać kursanta, że to miejsce właśnie dla niego!')),
                ('rules', models.TextField(blank=True, help_text='Link/i lub tekst. Możesz wkleić tutaj m.in. zasady uczestnictwa w zajęciach, regulamin płatności oraz obowiązujące w szkole Standardy Ochrony Małoletnich.', null=True)),
                ('default_registration_info_link', models.TextField(blank=True, help_text='Wklej tutaj link do Twojego systemu/formularza zapisów lub napisz informacje o sposobie zapisów na zajęcia. Link lub informacje zostaną automatycznie dodany do każdych nowych zajęć (będziesz mógł go zmienić przy konkretnym kursie).', null=True)),
                ('news', models.TextField(blank=True, help_text="Wpisz tu ważne komunikaty (np. 'W Wigilię nieczynne'). Ten tekst wyświetli się na profilu szkoły.", null=True, verbose_name='Aktualności')),
                ('accepts_multisport', models.BooleanField(default=False, verbose_name='Akceptujemy MultiSport')),
                ('accepts_medicover', models.BooleanField(default=False, verbose_name='Akceptujemy Medicover Sport (OK System)')),
                ('accepts_fitprofit', models.BooleanField(default=False, verbose_name='Akceptujemy FitProfit')),
                ('accepts_pzu_sport', models.BooleanField(default=False, verbose_name='Akceptujemy PZU Sport')),
                ('benefit_cards_info', models.TextField(blank=True, help_text='Tutaj wpisz informacje o ewentualnych dopłatach do kart lub kaucjach zwrotnych.', null=True, verbose_name='Informacje o kartach (dopłaty, kaucje)')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school', to=settings.AUTH_USER_MODEL)),
                ('styles', models.ManyToManyField(blank=True, related_name='schools', to='base.style')),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('entry_type', models.CharField(choices=[('pass', 'Karnet'), ('single', '1 wejście')], default='pass', max_length=10)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Czas trwania zajęć w minutach', null=True)),
                ('entries_per_week', models.PositiveIntegerField(blank=True, help_text='Ilość wejść w tygodniu (dla karnetów)', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list', to='base.school')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('pseudonym', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=base.utils.image_upload.instructor_image_path, validators=[base.utils.image_upload.ImageValidator(max_size_mb=5)])),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_instructors', to=settings.AUTH_USER_MODEL)),
                ('schools', models.ManyToManyField(related_name='instructors', to='base.school')),
                ('styles', models.ManyToManyField(blank=True, related_name='instructors', to='base.style')),
            ],
        ),
        migrations.CreateModel(
            name='DanceFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='base.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Pokaż klimat swojego miejsca, sale, recepcję, szatnie. Możesz dodać maksymalnie 9 zdjęć (najlepiej w orientacji poziomej).', upload_to=base.utils.image_upload.school_image_path, validators=[base.utils.image_upload.ImageValidator(max_size_mb=5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.school')),
            ],
        ),
        migrations.CreateModel(
            name='DanceClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, help_text="Opcjonalnie: doprecyzuj temat, np. 'Footwork', 'Musicality', 'Technika obrotów'.", max_length=100, null=True, verbose_name='Temat / Dopisek')),
                ('level', models.CharField(choices=[('BEGINNER', 'Od podstaw'), ('BASIC', 'Początkujący'), ('INTERMEDIATE', 'Średniozaawansowany'), ('ADVANCED', 'Zaawansowany'), ('PRO', 'Profesjonalny'), ('OPEN', 'Open (dla każdego)')], default='OPEN', max_length=20, verbose_name='Poziom zaawansowania')),
                ('group_type', models.CharField(blank=True, choices=[('FORMATION', 'Formacja'), ('PROJECT', 'Grupa zamknięta'), ('DANCE_CONTEST', 'Grupa turniejowa'), ('VIDEO_PROJECT', 'Video projekt')], max_length=20, null=True, verbose_name='Specyfika grupy (opcjonalne)')),
                ('min_age', models.PositiveIntegerField(help_text='Minimalny wiek uczestnika.', verbose_name='Wiek od (lat)')),
                ('max_age', models.PositiveIntegerField(blank=True, help_text='Zostaw puste, jeśli grupa nie ma górnej granicy (np. dla grupy 16+ lub dorosłych).', null=True, verbose_name='Wiek do (lat)')),
                ('day_of_week', models.CharField(blank=True, choices=[('monday', 'Poniedziałek'), ('tuesday', 'Wtorek'), ('wednesday', 'Środa'), ('thursday', 'Czwartek'), ('friday', 'Piątek'), ('saturday', 'Sobota'), ('sunday', 'Niedziela')], max_length=20)),
                ('starts_at', models.TimeField(verbose_name='Godzina startu')),
                ('ends_at', models.TimeField(help_text='W przypadku wydarzeń kilkudniowych: wpisz godzinę zakończenia CAŁEGO wydarzenia w ostatnim dniu jego trwania', verbose_name='Godzina końca')),
                ('description', models.TextField(blank=True, null=True)),
                ('periodic', models.BooleanField(default=True, verbose_name='Zajęcia cykliczne')),
                ('first_class_date', models.DateField(verbose_name='Data startu')),
                ('last_class_date', models.DateField(blank=True, null=True, verbose_name='Data końca')),
                ('can_join', models.BooleanField(default=True, help_text='Odznacz to pole, jeśli grupa jest już pełna lub zakończyły się do niej zapisy.')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('registration_info_link', models.TextField(blank=True, help_text='Link do zapisów lub instrukcja.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.dancefloor')),
                ('instructors', models.ManyToManyField(blank=True, related_name='classes', to='base.instructor')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='base.school')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='base.style')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='base.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('school', 'user')},
            },
        ),
    ]
